### PR TITLE
Support for user networks + docker v2 syntax.

### PR DESCRIPTION
**Pull request by sylus**
Drone does not work with Docker v2 syntax when using custom networks. Drone reverts to using the legacy network. However if any of the containers are needed by drone and in a custom network they can never communicate.

This largely means that Drone doesn't work with Docker v2. I have provided a way by environment variables where the ambassador container can assign itself to the right network.

There is currently also a bug in drone-exec preventing a build during one of the last 3 commits: 

```sh
# github.com/drone/drone-exec/runner
runner/match.go:29: s.Build.Deploy undefined (type *plugin.Build has no field or method Deploy)
```

### CODE REVIEW

**Comment by tboerger** [comment]
@bradrydzewski what do you think? Code-wise it looks ok to me.

**Comment by sylus** [comment]
I also added an associated pull request to drone itself to ensure the environment variable can be passed to all build environments.

**Comment by bradrydzewski** [comment]
you can override the default network in the yaml as seen below. Note that you might probably to toggle your build as trusted in the user interface.

```
build:
  image: golang
  net: foo

services:
  redis:
    image: redis
    net: foo
```

**Comment by sylus** [comment]
I have tried that recently as well but it doesn't work when setting net. I think it can be proved by testing out:

```sh
export DRONE_EXEC_NETWORKMODE=govdock_ci && cd /data/var/www && ./drone-exec --debug --pull --cache --clone --build <<EOF
{
    "system": {
        "link": "http://localhost:8000"
    },
    "workspace": {},
    "repo": {
        "owner": "garyburd",
        "name": "redigo",
        "full_name": "garyburd/redigo",
        "link_url": "https://github.com/garyburd/redigo",
        "clone_url": "git://github.com/garyburd/redigo.git",
        "trusted": true,
				"net": "govdock_ci"
    },
    "build": {
        "number": 1,
        "ref": "refs/heads/master",
        "commit": "d8dbe4d94f15fe89232e0402c6e8a0ddf21af3ab",
        "branch": "master"
    },
    "job": {
        "environment": {}
    },
    "config": "{ build: { image: 'golang:1.4.2', privileged: true, commands: ['cd redis', 'go build', 'go test -v']}, compose: { redis: { image: 'redis:2.8' } } }"
}
EOF
```

**Comment by bradrydzewski** [comment]
the redigo unit tests are hard-coded to use `localhost` ... but yes, we can set `net: host` which will instruct the containers to use the host machines networking and the tests will pass

```diff
./drone-exec --debug --pull --cache --clone --build <<EOF
{
    "system": {
        "link": "http://localhost:8000"
    },
    "workspace": {},
    "repo": {
        "owner": "garyburd",
        "name": "redigo",
        "full_name": "garyburd/redigo",
        "link_url": "https://github.com/garyburd/redigo",
        "clone_url": "git://github.com/garyburd/redigo.git"
    },
    "build": {
        "number": 1,
        "ref": "refs/heads/master",
        "commit": "d8dbe4d94f15fe89232e0402c6e8a0ddf21af3ab",
        "branch": "master"
    },
    "job": {
        "environment": {}
    },
+    "config": "{ build: { image: 'golang:1.4.2', net: host, commands: ['cd redis', 'go build', 'go test -v']}, compose: { redis: { image: 'redis:2.8', net: host } } }"
-    "config": "{ build: { image: 'golang:1.4.2', commands: ['cd redis', 'go build', 'go test -v']}, compose: { redis: { image: 'redis:2.8' } } }"
}
EOF
```

**Comment by sylus** [comment]
I ran the above command you wrote and the following containers ran:

```sh
ed06f273598b        redis:2.8                            "/entrypoint.sh redis"  hopeful_poincare
7ac252a80a3b        gliderlabs/alpine:3.1                "/bin/sleep 86400"       amazing_jones
```

docker inspect amazing_jones:

```sh
"NetworkMode": "default",
...
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "d6aceaa3d9a4c698a5a6c2a581a3a8090c6af532fe3c6578f13b5f450a70c2e0",
                    "EndpointID": "8147d68c688bba699ebaff38fe31d4ac6faa618c42d4d46420ea7f59837db680",
                    "Gateway": "10.1.25.1",
                    "IPAddress": "10.1.25.2",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:01:19:02"
                }
            }
```

**Comment by bradrydzewski** [comment]
sorry forgot to include one minor change below:

```diff
./drone-exec --debug --pull --cache --clone --build <<EOF
{
    "system": {
        "link": "http://localhost:8000"
    },
    "workspace": {},
    "repo": {
        "owner": "garyburd",
        "name": "redigo",
        "full_name": "garyburd/redigo",
        "link_url": "https://github.com/garyburd/redigo",
        "clone_url": "git://github.com/garyburd/redigo.git",
+        "trusted": true
    },
    "build": {
        "number": 1,
        "ref": "refs/heads/master",
        "commit": "d8dbe4d94f15fe89232e0402c6e8a0ddf21af3ab",
        "branch": "master"
    },
    "job": {
        "environment": {}
    },
+    "config": "{ build: { image: 'golang:1.4.2', net: host, commands: ['cd redis', 'go build', 'go test -v']}, compose: { redis: { image: 'redis:2.8', net: host } } }"
-    "config": "{ build: { image: 'golang:1.4.2', commands: ['cd redis', 'go build', 'go test -v']}, compose: { redis: { image: 'redis:2.8' } } }"
}
EOF
```

You will then see the following:

```
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "704db010a4946ecb1449ac55e76493669a298bc22a2cd2d960c44f7be17bc82d",
                    "EndpointID": "e9600f15d97388538dfa3827b65572031dc839fe6699f8f9e9e6d153b2cd1acc",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
```

**Comment by sylus** [comment]
1) Ran the following command:

```sh
./drone-exec --debug --pull --cache --clone --build <<EOF
{
    "system": {
        "link": "http://localhost:8000"
    },
    "workspace": {},
    "repo": {
        "owner": "garyburd",
        "name": "redigo",
        "full_name": "garyburd/redigo",
        "link_url": "https://github.com/garyburd/redigo",
        "clone_url": "git://github.com/garyburd/redigo.git",
        "trusted": true
    },
    "build": {
        "number": 1,
        "ref": "refs/heads/master",
        "commit": "d8dbe4d94f15fe89232e0402c6e8a0ddf21af3ab",
        "branch": "master"
    },
    "job": {
        "environment": {}
    },
    "config": "{ build: { image: 'golang:1.4.2', net: host, commands: ['cd redis', 'go build', 'go test -v']}, compose: { redis: { image: 'redis:2.8', net: host } } }"
}
EOF
```

2) Docker PS

```sh
a83d63803ae6        redis:2.8                            "/entrypoint.sh redis"   backstabbing_austin
062bf63b3648        gliderlabs/alpine:3.1                "/bin/sleep 86400"       dreamy_hugle
```

3) Docker Inspect dreamy_hugle

```sh
"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "f862ecc3967af87be0f2152000bae46544ad8303e09a7eeb96fec9b778b3c578",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/f862ecc3967a",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "2359a7e7beb32d38ee5781cb51c93f5f8c4929207036b7f3faa39f77854020f9",
            "Gateway": "10.1.25.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "10.1.25.2",
            "IPPrefixLen": 24,
            "IPv6Gateway": "",
            "MacAddress": "02:42:0a:01:19:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "d6aceaa3d9a4c698a5a6c2a581a3a8090c6af532fe3c6578f13b5f450a70c2e0",
                    "EndpointID": "2359a7e7beb32d38ee5781cb51c93f5f8c4929207036b7f3faa39f77854020f9",
                    "Gateway": "10.1.25.1",
                    "IPAddress": "10.1.25.2",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:01:19:02"
                }
            }
        }
```

**Comment by bradrydzewski** [comment]
this is expected, the ambassador container referenced above provides its own network, but it is not being used by the other containers, which override and use their own network.

**Comment by sylus** [comment]
The ambassador container is what calls the drone-git plugin and if I have cogs inside a custom network it can't be seen unless the ambassador container is on the correct network. That is what my 2 P.R.s accomplish.

Apologies as I am really trying to show and highlight the problem.

**Comment by bradrydzewski** [comment]
> The ambassador container is what calls the drone-git plugin and if I have cogs inside a custom network it can't be seen unless the ambassador container is on the correct network. That is what my 2 P.R.s accomplish.

you can specify the network for the clone container as well:

```
clone:
  net: host
```

**Comment by bradrydzewski** [comment]
the fix that I'm looking for is parity with the docker compose v2 yaml:
https://docs.docker.com/compose/networking/#specifying-custom-networks

this would be a yaml-driven approach and not an environment variable driven approach:

```
services:
  web:
    ports:
      - "8000:8000"
  db:
    image: postgres
    networks: foo

networks:
  default:
    driver: bridge
  foo:
    driver: bridge
```

this is a much more involved change because we need to create the networks, but also namespace them to prevent names from clashing. We also need to implement proper security to prevent the networks from using non-bridge drivers.

I really do appreciate the effort and willingness to chip in and provide a fix! I'm just looking for an implementation that is compliant with the docker compose yaml file that takes security and parallelism (name conflicts) into account.

I'm going to close this since it would not get merged as-is.

**Comment by sylus** [comment]
No worries I am happy to help and hopefully over time I can provide more meaningful P.R's. I only just started into Drone's architecture over the last little so hopefully will get better. I have to say it is alot of fun!

Also you completely solved my problem by mentioning that the git clone plugin could leverage `net` that was the missing piece I needed. With my yml file updated I don't need any of my P.R.'s.

Thanks so much for taking the time, your the best!

**Pull request closed without merging**
