### PR TITLE
Disable apt-get auto yes config to allow non-root containers

### PR DESCRIPTION
**Pull request by tam7t**
The `apt-get` configuration appears to be the blocker to allowing drone to run with non-root users. I'd argue that the convenience of being able to omit `--yes --force-yes` from the run list is not worth the restriction that `drone` images much be `root`.

Relevant [stackoverflow](http://superuser.com/questions/164553/automatically-answer-yes-when-using-apt-get-install) question.

### CODE REVIEW

**Comment by tboerger** [comment]
This will be a breaking change for builds that rely on this feature

**Comment by gtaylor** [comment]
Would be nice to make this configurable.

**Comment by tam7t** [comment]
I'll put some effort into making it configurable and hopefully have something tomorrow

**Comment by tam7t** [comment]
Closing in favor of https://github.com/drone/drone-exec/pull/10

**Pull request closed without merging**
