### PR TITLE
Whitelist drone-ecr.

### PR DESCRIPTION
**Pull request by johnrengelman**
Support for https://github.com/drone-plugins/drone-ecr/pull/1

### CODE REVIEW

**Comment by tboerger** [comment]
Time to write a helper func

**Comment by johnrengelman** [comment]
Would be ideal if this was user configurable via an envvar.

**Comment by johnrengelman** [comment]
I've put together a series of PRs that I think would allow a user to use the `ESCALATE_PLUGIN_FILTER` envvar to select which plugins can will be run with escalated privileges:
drone: https://github.com/drone/drone/pull/1405
drone-plugin-go: https://github.com/drone/drone-plugin-go/pull/5
drone-exec: https://github.com/drone/drone-exec/pull/20

**Comment by bradrydzewski** [comment]
LGTM

**Pull request merged**
